
services:
  mysql:
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_USER: ${ENV_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_USER}
      MYSQL_PASSWORD: ${ENV_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - user-service-db:/var/lib/mysql

volumes:
  user-service-db: